### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by yamanash** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#13]
To be done by Thursday before class.
Assigned: All members 
![image](https://user-images.githubusercontent.com/31657679/152897671-362a50d3-513d-4abc-b7e4-5fdefd1667ed.png)

**Comment by whitneytwh** [comment]
Individual Sequence Diagrams Completed - 18/2/2022

<img width="115" alt="SequenceDiagram" src="https://user-images.githubusercontent.com/72186676/154701546-75d6d10d-8d90-4f0f-b827-8845519b0616.PNG">
<img width="120" alt="SequenceDiagramAppendix" src="https://user-images.githubusercontent.com/72186676/154701556-1313625f-e807-4370-a423-9183d01f142a.PNG">
