### ISSUE TITLE
Section 4 Software Architecture

### ISSUE THREAD

**Issue by yamanash** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#19]
4.1 [ ] ASP.NET MVC Pattern
4.2 [ ] Usage of Architecture pattern
4.3 [ ] Architecture Evaluation

**Comment by whitneytwh** [comment]
Architecture Section Completed - 18/2/2022

<img width="209" alt="ArchitecturePattern" src="https://user-images.githubusercontent.com/72186676/154709896-ef09a2b4-d6c4-4f2c-ad32-5fe13e954ca6.PNG">
