### ISSUE TITLE
Section 5 Software View (Diagrams)

### ISSUE THREAD

**Issue by yamanash** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#20]
5.1 [ ] Class Diagrams
5.2 [ ] Component Diagram

**Comment by whitneytwh** [comment]
Class Diagrams & Component Diagram Completed - 18/2/2022

<img width="269" alt="ClassDiagram" src="https://user-images.githubusercontent.com/72186676/154702736-36bbda92-21ac-4db1-8829-3d8faccf3e28.PNG">
<img width="268" alt="ComponentDiagram" src="https://user-images.githubusercontent.com/72186676/154702744-006e3bdc-4145-4200-8d15-9f012d783ba5.PNG">
