### ISSUE TITLE
What can be improved? (Learning Points)

### ISSUE THREAD

**Issue by Nikoswee** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#47]
What should be done to improve from Sprint 1:

- Communication with other teams and client for requirements gathering and project coordination
- Plan ahead of time
- Set proper deadlines
- Complete assigned tasks within the deadline
- Implementation to be done following the diagrams for better consistency for everyone in the team and other teams to follow

**Comment by Kenrick78** [comment]
Communicating with other teams and clients for requirements gathering and project coordination

**Comment by Nikoswee** [comment]
Plan ahead of time, set proper deadlines and complete within the deadline

**Comment by ZhengZhengZhengZheng** [comment]
Can do codes together with diagrams for better consistency
