### ISSUE TITLE
What went not so well

### ISSUE THREAD

**Issue by Nikoswee** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#48]
Things that we did not so well for Sprint 1:

- Diagrams is inconsistent with code
- Diagrams was not drawn properly due to confusion
- Bad time management, making the project very rushed
- Miscommunications with client and other groups for features implementations
- UI should be consistent among the teams
- Demonstration to the client should follow a logical flow such as story telling
- Choose feature to develop for prototype was not a fully implemented one due to needed other features to be completed first

**Comment by ZhengZhengZhengZheng** [comment]
Diagrams might be inconsistent with code

**Comment by Nikoswee** [comment]
Bad time management, project was rushed

**Comment by Kenrick78** [comment]
Miscommunication with clients and other groups for features implementations

**Comment by skyblue012** [comment]
The UI should be consistent among the teams

**Comment by skyblue012** [comment]
The demo should follow a logical flow
