### ISSUE TITLE
What went well

### ISSUE THREAD

**Issue by Nikoswee** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#49]
Things that we did well for Sprint 1:

- There was good communication within our group
- Everyone participated in the report
- Managed to come up with the correct user features that is aligned with our user requirements
- Good team coordination for deliverables to be completed
- Features being proposed and implemented progressively
- Presentation of wireframe and demonstration of prototype to client went smoothly
- Everybody attended meeting on time when scheduled
- Everyone did their part and help one another when needed

**Comment by Nikoswee** [comment]
There was good communication within our group

**Comment by skyblue012** [comment]
Everyone participate in the report

**Comment by Nikoswee** [comment]
Managed to come up with the correct user features to align with our user requirements

**Comment by Kenrick78** [comment]
Good team coordination for deliverables to be completed and features being proposed and implemented progressively

**Comment by ZhengZhengZhengZheng** [comment]
Presentation of prototype went smoothly
