### ISSUE TITLE
Issue 14: Reassign tasks and features to team members for sprint 2

### ISSUE THREAD

**Issue by ZhengZhengZhengZheng** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#54]
- [x] Assignment of Navigation of Trips
- [x] Local Tourist Attractions Suggestion based on Current Location
- [x] View List of Local Tourist Attractions
- [x] Search Bar with Additional Parameters for Local Tourist Attraction
- [x] Allow Users to Upvote on Local Tourist Attraction

**Comment by Nikoswee** [comment]
Assignment done
