### ISSUE TITLE
Section 1: Introduction

### ISSUE THREAD

**Issue by yamanash** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#8]
-Whitney and Sabrina

To be done by 10 feb

**Comment by whitneytwh** [comment]
Introduction Completed - 18/2/2022

<img width="434" alt="Introduction" src="https://user-images.githubusercontent.com/72186676/154708851-caf92a45-9ae2-4944-b325-20d2142bee8b.PNG">
