### ISSUE TITLE
Issue 22: UF4 - Search bar with additional parameters for Local Tourist Attractions

### ISSUE THREAD

**Issue by kendricklq** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#81]
- [x] Add Attraction View, Model and Controller
- [x] Put search bar in View
- [x] Create dummy data
- [x] Code search function based on dummy data
- [x] Customize CSS and View page appearance
- [x] Add attraction images
- [x] Integrate to team's View, Model and Controller

**Comment by ZhengZhengZhengZheng** [comment]
Completed feature
