### ISSUE TITLE
Section 2: User requirements -

### ISSUE THREAD

**Issue by yamanash** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#9]
To be done by 10 feb

- [x] Use case diagram
- [x] Use case description
- [x] Functional Req
- [x] Non-Functional Req 

Assigned: May, Tsin and Gaius

**Comment by yamanash** [comment]
![image](https://user-images.githubusercontent.com/32984454/153818348-fa4c8edf-032f-4684-964a-c58ead26fe9d.png)
![image](https://user-images.githubusercontent.com/32984454/153818357-61a43a47-d192-4c39-b764-18399081af18.png)
![image](https://user-images.githubusercontent.com/32984454/153818371-7c2c26d8-42e6-47c3-965a-0940c8ee0a09.png)
![image](https://user-images.githubusercontent.com/32984454/153818385-83ce91cf-536a-411f-8569-e66735e75a14.png)
![image](https://user-images.githubusercontent.com/32984454/153818395-b76b3e00-6568-41fb-b68f-d54f98cc3f14.png)
![image](https://user-images.githubusercontent.com/32984454/153818399-5c4ed7f1-656e-4408-ae51-d6862e21b0ec.png)
![image](https://user-images.githubusercontent.com/32984454/153818411-3bffcc37-d878-466e-b1da-bbdac79ffbd8.png)
![image](https://user-images.githubusercontent.com/32984454/153818430-426512ce-0489-4012-a85c-e93b85704699.png)


All the use case descriptions completed.

**Comment by whitneytwh** [comment]
Functional & Non-functional, Use Case Diagram & Description Completed - 18/2/2022

<img width="245" alt="FunctionNon_UseCase" src="https://user-images.githubusercontent.com/72186676/154709371-32e564e0-7750-44ea-bcdf-acef787456a2.PNG">
